// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pubsub.proto
#ifndef GRPC_pubsub_2eproto__INCLUDED
#define GRPC_pubsub_2eproto__INCLUDED

#include "pubsub.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace pb {

// PubSubAPI provides a libp2p pubsub API and is equivalent to go-ipfs
// `ipfs pubsub` subset of commands.
class PubSubAPI final {
 public:
  static constexpr char const* service_full_name() {
    return "pb.PubSubAPI";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // PubSub allows controlling libp2p pubsub topics and subscriptions using
    // a bidirectional streaming API
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::pb::PubSubRequest, ::pb::PubSubResponse>> PubSub(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::pb::PubSubRequest, ::pb::PubSubResponse>>(PubSubRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::pb::PubSubRequest, ::pb::PubSubResponse>> AsyncPubSub(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::pb::PubSubRequest, ::pb::PubSubResponse>>(AsyncPubSubRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::pb::PubSubRequest, ::pb::PubSubResponse>> PrepareAsyncPubSub(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::pb::PubSubRequest, ::pb::PubSubResponse>>(PrepareAsyncPubSubRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // PubSub allows controlling libp2p pubsub topics and subscriptions using
      // a bidirectional streaming API
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PubSub(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::pb::PubSubRequest,::pb::PubSubResponse>* reactor) = 0;
      #else
      virtual void PubSub(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::pb::PubSubRequest,::pb::PubSubResponse>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::pb::PubSubRequest, ::pb::PubSubResponse>* PubSubRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::pb::PubSubRequest, ::pb::PubSubResponse>* AsyncPubSubRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::pb::PubSubRequest, ::pb::PubSubResponse>* PrepareAsyncPubSubRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::pb::PubSubRequest, ::pb::PubSubResponse>> PubSub(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::pb::PubSubRequest, ::pb::PubSubResponse>>(PubSubRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::pb::PubSubRequest, ::pb::PubSubResponse>> AsyncPubSub(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::pb::PubSubRequest, ::pb::PubSubResponse>>(AsyncPubSubRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::pb::PubSubRequest, ::pb::PubSubResponse>> PrepareAsyncPubSub(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::pb::PubSubRequest, ::pb::PubSubResponse>>(PrepareAsyncPubSubRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PubSub(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::pb::PubSubRequest,::pb::PubSubResponse>* reactor) override;
      #else
      void PubSub(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::pb::PubSubRequest,::pb::PubSubResponse>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::pb::PubSubRequest, ::pb::PubSubResponse>* PubSubRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::pb::PubSubRequest, ::pb::PubSubResponse>* AsyncPubSubRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::pb::PubSubRequest, ::pb::PubSubResponse>* PrepareAsyncPubSubRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PubSub_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // PubSub allows controlling libp2p pubsub topics and subscriptions using
    // a bidirectional streaming API
    virtual ::grpc::Status PubSub(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::pb::PubSubResponse, ::pb::PubSubRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_PubSub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PubSub() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PubSub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PubSub(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::pb::PubSubResponse, ::pb::PubSubRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPubSub(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::pb::PubSubResponse, ::pb::PubSubRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PubSub<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PubSub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PubSub() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::pb::PubSubRequest, ::pb::PubSubResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->PubSub(context); }));
    }
    ~ExperimentalWithCallbackMethod_PubSub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PubSub(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::pb::PubSubResponse, ::pb::PubSubRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::pb::PubSubRequest, ::pb::PubSubResponse>* PubSub(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::pb::PubSubRequest, ::pb::PubSubResponse>* PubSub(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_PubSub<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_PubSub<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PubSub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PubSub() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PubSub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PubSub(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::pb::PubSubResponse, ::pb::PubSubRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PubSub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PubSub() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PubSub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PubSub(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::pb::PubSubResponse, ::pb::PubSubRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPubSub(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PubSub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PubSub() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->PubSub(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_PubSub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PubSub(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::pb::PubSubResponse, ::pb::PubSubRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* PubSub(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* PubSub(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace pb


#endif  // GRPC_pubsub_2eproto__INCLUDED
